object TpmLossForm: TTpmLossForm
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'TPM Loss Code'
  ClientHeight = 634
  ClientWidth = 1020
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Scaled = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 19
  object pnlTitle: TPanel
    Left = 10
    Top = 10
    Width = 1000
    Height = 48
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'TPM Loss Code'
    Color = 192
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
  end
  object btnCancel: TButton
    Left = 898
    Top = 18
    Width = 102
    Height = 32
    Cancel = True
    Caption = 'Cancel'
    ModalResult = 2
    TabOrder = 1
  end
  object hdrState: TPanel
    Left = 10
    Top = 62
    Width = 112
    Height = 38
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'EQP STATE'
    Color = 10040064
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 2
  end
  object hdrIndex: TPanel
    Left = 122
    Top = 62
    Width = 118
    Height = 38
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'TP Index'
    Color = 10040064
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 3
  end
  object hdrDescription: TPanel
    Left = 240
    Top = 62
    Width = 524
    Height = 38
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Description'
    Color = 10040064
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 4
  end
  object hdrCode: TPanel
    Left = 764
    Top = 62
    Width = 112
    Height = 38
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Code'
    Color = 10040064
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 5
  end
  object hdrChoice: TPanel
    Left = 876
    Top = 62
    Width = 134
    Height = 38
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Choice'
    Color = 10040064
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 6
  end
  object pnlDown: TPanel
    Left = 10
    Top = 100
    Width = 112
    Height = 500
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'DOWN'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 7
  end
  object idx0300: TPanel
    Left = 122
    Top = 100
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'BM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 8
  end
  object desc0300: TPanel
    Left = 240
    Top = 100
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Breakdown maintenance'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 9
  end
  object code0300: TPanel
    Left = 764
    Top = 100
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '0300'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 10
  end
  object btnSelect0300: TButton
    Left = 886
    Top = 108
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 11
    OnClick = btnSelect0300Click
  end
  object idx1200: TPanel
    Left = 122
    Top = 150
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'PM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 12
  end
  object desc1200: TPanel
    Left = 240
    Top = 150
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Scheduled PM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 13
  end
  object code1200: TPanel
    Left = 764
    Top = 150
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1200'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 14
  end
  object btnSelect1200: TButton
    Left = 886
    Top = 158
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 15
    OnClick = btnSelect1200Click
  end
  object idx1510: TPanel
    Left = 122
    Top = 200
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'PM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 16
  end
  object desc1510: TPanel
    Left = 240
    Top = 200
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Unscheduled PM - Equipment inspection'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 17
  end
  object code1510: TPanel
    Left = 764
    Top = 200
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1510'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 18
  end
  object btnSelect1510: TButton
    Left = 886
    Top = 208
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 19
    OnClick = btnSelect1510Click
  end
  object idx1520: TPanel
    Left = 122
    Top = 250
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'PM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 20
  end
  object desc1520: TPanel
    Left = 240
    Top = 250
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Unscheduled PM - Quality inspection'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 21
  end
  object code1520: TPanel
    Left = 764
    Top = 250
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1520'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 22
  end
  object btnSelect1520: TButton
    Left = 886
    Top = 258
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 23
    OnClick = btnSelect1520Click
  end
  object idx1720: TPanel
    Left = 122
    Top = 300
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'CM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 24
  end
  object desc1720: TPanel
    Left = 240
    Top = 300
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Equipment improvement maintenance (EE)'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 25
  end
  object code1720: TPanel
    Left = 764
    Top = 300
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1720'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 26
  end
  object btnSelect1720: TButton
    Left = 886
    Top = 308
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 27
    OnClick = btnSelect1720Click
  end
  object idx1730: TPanel
    Left = 122
    Top = 350
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'CM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 28
  end
  object desc1730: TPanel
    Left = 240
    Top = 350
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Process improvement maintenance (EI)'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 29
  end
  object code1730: TPanel
    Left = 764
    Top = 350
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1730'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 30
  end
  object btnSelect1730: TButton
    Left = 886
    Top = 358
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 31
    OnClick = btnSelect1730Click
  end
  object idx1400: TPanel
    Left = 122
    Top = 400
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'CM'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 32
  end
  object desc1400: TPanel
    Left = 240
    Top = 400
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'New product setup'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 33
  end
  object code1400: TPanel
    Left = 764
    Top = 400
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '1400'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 34
  end
  object btnSelect1400: TButton
    Left = 886
    Top = 408
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 35
    OnClick = btnSelect1400Click
  end
  object idx4110: TPanel
    Left = 122
    Top = 450
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Minor stop'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 36
  end
  object desc4110: TPanel
    Left = 240
    Top = 450
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Minor stop'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 37
  end
  object code4110: TPanel
    Left = 764
    Top = 450
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '4110'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 38
  end
  object btnSelect4110: TButton
    Left = 886
    Top = 458
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 39
    OnClick = btnSelect4110Click
  end
  object idx3500: TPanel
    Left = 122
    Top = 500
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Material'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 40
  end
  object desc3500: TPanel
    Left = 240
    Top = 500
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Material replacement'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 41
  end
  object code3500: TPanel
    Left = 764
    Top = 500
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '3500'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 42
  end
  object btnSelect3500: TButton
    Left = 886
    Top = 508
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 43
    OnClick = btnSelect3500Click
  end
  object idx5100: TPanel
    Left = 122
    Top = 550
    Width = 118
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Material'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 44
  end
  object desc5100: TPanel
    Left = 240
    Top = 550
    Width = 524
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = 'Material downtime'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 45
  end
  object code5100: TPanel
    Left = 764
    Top = 550
    Width = 112
    Height = 50
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Caption = '5100'
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 46
  end
  object btnSelect5100: TButton
    Left = 886
    Top = 558
    Width = 114
    Height = 34
    Caption = 'Select'
    TabOrder = 47
    OnClick = btnSelect5100Click
  end
  object lblStatus: TLabel
    Left = 16
    Top = 608
    Width = 992
    Height = 22
    AutoSize = False
    Caption = 'Paused. Select a reason to enter Manual mode.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clGray
    Font.Height = -14
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
end
