//---------------------------------------------------------------------------

#ifndef FormTeachingH
#define FormTeachingH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <jpeg.hpp>
#include <Dialogs.hpp>
#include "AdvSmoothButton.hpp"
#include "AdvSmoothPanel.hpp"
#include "AdvSmoothToggleButton.hpp"
#include <Vcl.ComCtrls.hpp>
#include <DateUtils.hpp>

//---------------------------------------------------------------------------
typedef struct{
	AnsiString str_x;
	AnsiString str_y;
	AnsiString str_z;
	AnsiString point;
	int index;
	int total;
	int tag;
}TEACHING;


typedef struct{
	int Top;
	int Bottom;
	int Left;
	int Right;
}TRAY_POSITION;




class TteachForm : public TForm
{
__published:	// IDE-managed Components
	TImage *Image12;
	TAdvSmoothPanel *AdvSmoothPanel6;
	TAdvSmoothPanel *grp_process;
	TAdvSmoothPanel *t1;
	TAdvSmoothPanel *t2;
	TAdvSmoothPanel *t3;
	TAdvSmoothPanel *t20;
	TAdvSmoothPanel *t17;
	TAdvSmoothPanel *t18;
	TAdvSmoothPanel *t19;
	TAdvSmoothPanel *t16;
	TAdvSmoothPanel *t13;
	TAdvSmoothPanel *t14;
	TAdvSmoothPanel *t15;
	TAdvSmoothPanel *t12;
	TAdvSmoothPanel *t9;
	TAdvSmoothPanel *t10;
	TAdvSmoothPanel *t11;
	TAdvSmoothPanel *t8;
	TAdvSmoothPanel *t5;
	TAdvSmoothPanel *t6;
	TAdvSmoothPanel *t7;
	TAdvSmoothPanel *t4;
	TAdvSmoothPanel *t21;
	TAdvSmoothPanel *t22;
	TAdvSmoothPanel *t23;
	TAdvSmoothPanel *t24;
	TEdit *gpEdit9;
	TEdit *gpEdit10;
	TPanel *Panel2;
	TPanel *Panel1;
	TPanel *Panel3;
	TAdvSmoothPanel *s74;
	TAdvSmoothPanel *s73;
	TAdvSmoothPanel *s75;
	TAdvSmoothPanel *s76;
	TAdvSmoothPanel *s77;
	TAdvSmoothPanel *s78;
	TEdit *gpEdit7;
	TEdit *gpEdit8;
	TPanel *Panel24;
	TPanel *Panel25;
	TPanel *Panel26;
	TAdvSmoothPanel *s80;
	TAdvSmoothPanel *s79;
	TAdvSmoothPanel *s81;
	TAdvSmoothPanel *s82;
	TAdvSmoothPanel *s83;
	TAdvSmoothPanel *s84;
	TAdvSmoothPanel *s86;
	TAdvSmoothPanel *s85;
	TAdvSmoothPanel *s87;
	TAdvSmoothPanel *s88;
	TAdvSmoothPanel *s89;
	TAdvSmoothPanel *s90;
	TAdvSmoothPanel *s92;
	TAdvSmoothPanel *s91;
	TAdvSmoothPanel *s93;
	TAdvSmoothPanel *s94;
	TAdvSmoothPanel *s95;
	TAdvSmoothPanel *s96;
	TPanel *Panel28;
	TEdit *gpEdit17;
	TEdit *gpEdit18;
	TPanel *Panel27;
	TLabel *Label7;
	TLabel *Label2;
	TLabel *Label1;
	TComboBox *tCombo;
	TPanel *Panel10;
	TComboBox *sCombo;
	TPanel *Panel20;
	TPanel *pselect;
	TAdvSmoothPanel *AdvSmoothPanel1;
	TLabel *Label3;
	TAdvSmoothPanel *AdvSmoothPanel3;
	TAdvSmoothPanel *AdvSmoothPanel2;
	TPanel *Panel35;
	TPanel *px1;
	TEdit *speedEdit;
	TPanel *Panel39;
	TPanel *Panel31;
	TPanel *py;
	TPanel *Panel33;
	TPanel *pz;
	TPanel *Panel37;
	TPanel *Panel29;
	TPanel *perr;
	TPanel *pspeed;
	TLabel *Label4;
	TLabel *Label5;
	TAdvSmoothPanel *AdvSmoothPanel4;
	TLabel *Label6;
	TAdvSmoothPanel *AdvSmoothPanel5;
	TLabel *Label11;
	TPanel *Panel30;
	TImage *Image1;
	TLabel *CLR1;
	TPanel *pdn1;
	TPanel *pup1;
	TPanel *pflow1;
	TPanel *pclose1;
	TPanel *pcell1;
	TPanel *popen1;
	TAdvSmoothButton *AdvSmoothButton12;
	TAdvSmoothButton *AdvSmoothButton11;
	TAdvSmoothButton *AdvSmoothButton13;
	TAdvSmoothButton *AdvSmoothButton14;
	TLabel *Label12;
	TLabel *Label13;
	TCheckBox *disableChk1;
	TPanel *Panel40;
	TImage *Image2;
	TLabel *Label14;
	TLabel *Label15;
	TLabel *Label16;
	TPanel *pdn2;
	TPanel *pup2;
	TPanel *pflow2;
	TPanel *pclose2;
	TPanel *pcell2;
	TPanel *popen2;
	TAdvSmoothButton *AdvSmoothButton15;
	TAdvSmoothButton *AdvSmoothButton16;
	TAdvSmoothButton *AdvSmoothButton17;
	TAdvSmoothButton *AdvSmoothButton18;
	TCheckBox *disableChk2;
	TPanel *Panel47;
	TImage *Image3;
	TLabel *Label17;
	TLabel *Label18;
	TLabel *Label19;
	TPanel *pdn3;
	TPanel *pup3;
	TPanel *pflow3;
	TPanel *pclose3;
	TPanel *pcell3;
	TPanel *popen3;
	TAdvSmoothButton *AdvSmoothButton19;
	TAdvSmoothButton *AdvSmoothButton20;
	TAdvSmoothButton *AdvSmoothButton21;
	TAdvSmoothButton *AdvSmoothButton22;
	TCheckBox *disableChk3;
	TPanel *Panel54;
	TImage *Image4;
	TLabel *Label20;
	TLabel *Label21;
	TLabel *Label22;
	TPanel *pdn4;
	TPanel *pup4;
	TPanel *pflow4;
	TPanel *pclose4;
	TPanel *pcell4;
	TPanel *popen4;
	TAdvSmoothButton *AdvSmoothButton23;
	TAdvSmoothButton *AdvSmoothButton24;
	TAdvSmoothButton *AdvSmoothButton25;
	TAdvSmoothButton *AdvSmoothButton26;
	TCheckBox *disableChk4;
	TPanel *Panel61;
	TImage *Image5;
	TLabel *Label23;
	TLabel *Label24;
	TLabel *Label25;
	TPanel *pdn5;
	TPanel *pup5;
	TPanel *pflow5;
	TPanel *pclose5;
	TPanel *pcell5;
	TPanel *popen5;
	TAdvSmoothButton *AdvSmoothButton27;
	TAdvSmoothButton *AdvSmoothButton28;
	TAdvSmoothButton *AdvSmoothButton29;
	TAdvSmoothButton *AdvSmoothButton30;
	TCheckBox *disableChk5;
	TPanel *Panel68;
	TImage *Image6;
	TLabel *Label26;
	TLabel *Label27;
	TLabel *Label28;
	TPanel *pdn6;
	TPanel *pup6;
	TPanel *pflow6;
	TPanel *pclose6;
	TPanel *pcell6;
	TPanel *popen6;
	TAdvSmoothButton *AdvSmoothButton31;
	TAdvSmoothButton *AdvSmoothButton32;
	TAdvSmoothButton *AdvSmoothButton33;
	TAdvSmoothButton *AdvSmoothButton34;
	TCheckBox *disableChk6;
	TAdvSmoothButton *AdvSmoothButton35;
	TAdvSmoothButton *AdvSmoothButton36;
	TLabel *Label29;
	TLabel *Label30;
	TAdvSmoothButton *AdvSmoothButton37;
	TAdvSmoothButton *AdvSmoothButton38;
	TLabel *Label31;
	TLabel *Label32;
	TMemo *tea_memo;
	TTimer *teachingTimer;
	TAdvSmoothButton *AdvSmoothButton4;
	TAdvSmoothButton *AdvSmoothButton3;
	TOpenDialog *OpenDialog;
	TSaveDialog *SaveDialog;
	TAdvSmoothButton *AdvSmoothButton_ServoOff;
	TAdvSmoothButton *waitBtn;
	TRadioButton *rdo48;
	TRadioButton *rdo96;
	TPanel *Panel9;
	TPanel *Panel8;
	TPanel *Panel7;
	TEdit *gpEdit14;
	TEdit *gpEdit13;
	TEdit *gpEdit11;
	TEdit *gpEdit12;
	TPanel *Panel4;
	TPanel *Panel5;
	TPanel *Panel6;
	TPanel *Panel11;
	TPanel *Panel12;
	TPanel *Panel13;
	TEdit *gpEdit16;
	TEdit *gpEdit15;
	TEdit *gpEdit1;
	TEdit *gpEdit2;
	TPanel *Panel14;
	TPanel *Panel15;
	TPanel *Panel16;
	TEdit *gpEdit3;
	TEdit *gpEdit4;
	TPanel *Panel17;
	TPanel *Panel18;
	TPanel *Panel19;
	TEdit *gpEdit5;
	TEdit *gpEdit6;
	TPanel *Panel21;
	TPanel *Panel22;
	TPanel *Panel23;
	TAdvSmoothPanel *s1;
	TAdvSmoothPanel *s2;
	TAdvSmoothPanel *s3;
	TAdvSmoothPanel *s5;
	TAdvSmoothPanel *s6;
	TAdvSmoothPanel *s4;
	TAdvSmoothPanel *s7;
	TAdvSmoothPanel *s8;
	TAdvSmoothPanel *s9;
	TAdvSmoothPanel *s11;
	TAdvSmoothPanel *s12;
	TAdvSmoothPanel *s10;
	TAdvSmoothPanel *s13;
	TAdvSmoothPanel *s14;
	TAdvSmoothPanel *s15;
	TAdvSmoothPanel *s17;
	TAdvSmoothPanel *s18;
	TAdvSmoothPanel *s16;
	TAdvSmoothPanel *s19;
	TAdvSmoothPanel *s20;
	TAdvSmoothPanel *s21;
	TAdvSmoothPanel *s23;
	TAdvSmoothPanel *s24;
	TAdvSmoothPanel *s22;
	TAdvSmoothPanel *s53;
	TAdvSmoothPanel *s54;
	TAdvSmoothPanel *s52;
	TAdvSmoothPanel *s49;
	TAdvSmoothPanel *s50;
	TAdvSmoothPanel *s51;
	TAdvSmoothPanel *s59;
	TAdvSmoothPanel *s60;
	TAdvSmoothPanel *s58;
	TAdvSmoothPanel *s55;
	TAdvSmoothPanel *s56;
	TAdvSmoothPanel *s57;
	TAdvSmoothPanel *s65;
	TAdvSmoothPanel *s66;
	TAdvSmoothPanel *s64;
	TAdvSmoothPanel *s61;
	TAdvSmoothPanel *s62;
	TAdvSmoothPanel *s63;
	TAdvSmoothPanel *s71;
	TAdvSmoothPanel *s72;
	TAdvSmoothPanel *s70;
	TAdvSmoothPanel *s67;
	TAdvSmoothPanel *s68;
	TAdvSmoothPanel *s69;
	TAdvSmoothPanel *s30;
	TAdvSmoothPanel *s27;
	TAdvSmoothPanel *s28;
	TAdvSmoothPanel *s29;
	TAdvSmoothPanel *s26;
	TAdvSmoothPanel *s25;
	TAdvSmoothPanel *s36;
	TAdvSmoothPanel *s33;
	TAdvSmoothPanel *s34;
	TAdvSmoothPanel *s35;
	TAdvSmoothPanel *s32;
	TAdvSmoothPanel *s31;
	TAdvSmoothPanel *s42;
	TAdvSmoothPanel *s39;
	TAdvSmoothPanel *s40;
	TAdvSmoothPanel *s41;
	TAdvSmoothPanel *s38;
	TAdvSmoothPanel *s37;
	TAdvSmoothPanel *s48;
	TAdvSmoothPanel *s45;
	TAdvSmoothPanel *s46;
	TAdvSmoothPanel *s47;
	TAdvSmoothPanel *s44;
	TAdvSmoothPanel *s43;
	TAdvSmoothButton *openBtn;
	TLabel *Label8;
	TLabel *Label9;
	TLabel *Label10;
	TButton *Button1;
	TButton *Button2;
	TButton *Button3;
	TButton *Button4;
	TButton *Button5;
	TButton *Button6;
	TAdvSmoothButton *AdvSmoothButton_ServoOn;
	TAdvSmoothButton *applyBtn;
	TAdvSmoothButton *AdvSmoothButton_Zup;
	TAdvSmoothButton *homeBtn;
	TAdvSmoothButton *stopBtn;
	TAdvSmoothButton *AdvSmoothButton_Reset;
	TPanel *popen;
	TPanel *Panel32;
	TPanel *Panel34;
	TPanel *pOnX1;
	TPanel *pOnY;
	TPanel *pOnZ;
	TPanel *pOnX2;
	TPanel *Panel36;
	TPanel *pOrgX1;
	TPanel *pOrgY;
	TPanel *pOrgZ;
	TPanel *pOrgX2;
	TPanel *Panel38;
	TPanel *pErrorX1;
	TPanel *pErrorY;
	TPanel *pErrorZ;
	TPanel *pErrorX2;
	TPanel *Panel42;
	TPanel *pLspX1;
	TPanel *pLspY;
	TPanel *pLspZ;
	TPanel *pLspX2;
	TPanel *Panel43;
	TPanel *pLsnX1;
	TPanel *pLsnY;
	TPanel *pLsnZ;
	TPanel *pLsnX2;
	TPanel *Panel44;
	TPanel *px2;
	TLabel *Label33;
	TPanel *Panel45;
	TMemo *Memo_Ko;
	TMemo *Memo_En;
	TMemo *Memo_Hu;
	TAdvSmoothButton *AdvSmoothButton_CenteringDown;
	TPanel *Panel41;
	TPanel *Panel_speedEdit;
	TAdvSmoothButton *AdvSmoothButton_LoadFactorInfo;
	TPanel *pOnG1;
	TPanel *pOnG2;
	TPanel *pErrorG1;
	TPanel *pErrorG2;
	TPanel *pLsnG1;
	TPanel *pLsnG2;
	TPanel *pOrgG1;
	TPanel *pOrgG2;
	TPanel *pLspG1;
	TPanel *pLspG2;
	TPanel *Panel46;
	TPanel *pg1;
	TPanel *Panel49;
	TPanel *pg2;
	TAdvSmoothPanel *AdvSmoothPanel7;
	TLabel *Label34;
	TListView *searchList;
	TMemo *resultMemo;
	TEdit *gpEdit19;
	TPanel *Panel52;
	TPanel *Panel53;
	TEdit *gpEdit20;
	TAdvSmoothPanel *AdvSmoothPanel8;
	TLabel *Label50;
	TLabel *Label35;
	TEdit *typeEdit1;
	TLabel *Label36;
	TComboBox *typeCombo;
	TLabel *Label37;
	TRadioButton *msa96;
	TRadioButton *msa48;
	TLabel *Label38;
	TLabel *Label48;
	TEdit *typeEdit6;
	TLabel *Label39;
	TEdit *typeEdit5;
	TLabel *Label40;
	TEdit *typeEdit4;
	TLabel *Label41;
	TEdit *typeEdit3;
	TLabel *Label42;
	TEdit *typeEdit2;
	TLabel *Label49;
	TLabel *Label43;
	TEdit *typeEdit11;
	TLabel *Label44;
	TEdit *typeEdit10;
	TLabel *Label45;
	TEdit *typeEdit9;
	TLabel *Label46;
	TEdit *typeEdit8;
	TLabel *Label47;
	TEdit *typeEdit7;
	TAdvSmoothButton *AdvSmoothButton1;
	TAdvSmoothButton *AdvSmoothButton2;
	TLabel *Label52;
	TLabel *Label53;
	TLabel *Label54;
	TLabel *Label55;
	TRadioButton *rdo482;
	TRadioButton *msa482;
	TButton *Button7;
	TButton *Button8;
	TLabel *Label51;
	TLabel *Label56;
	TButton *Button9;
	TButton *Button10;
	TRadioButton *msa242;
	TPanel *Panel73;
	TPanel *Panel69;
	TEdit *acclSpeedEdit;
	TEdit *dcclSpeedEdit;
	TLabel *lblLoadFactor5;
	TLabel *lblLoadFactor6;
	TLabel *Label58;
	TLabel *lblLoadFactor1;
	TLabel *Label60;
	TLabel *lblLoadFactor4;
	TLabel *lblLoadFactor3;
	TLabel *lblLoadFactor2;
	TGroupBox *GroupBox1;
	TButton *btnZAxisUp;
	TButton *btnZAxisDown;
	TRadioButton *rdo242;
	TRadioButton *msa962;
	TAdvSmoothButton *btnKeyLock;
	TTimer *unchuckTimer;
	TTimer *unchuckAllTimer;
	TAdvSmoothPanel *pnlMovingAlarm;
	TLabel *Label57;
	TLabel *Label69;
	TAdvSmoothPanel *pnlMovingAlarm2;
	TLabel *Label59;
	TLabel *Label61;
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall sClick(TObject *Sender);
	void __fastcall tClick(TObject *Sender);
	void __fastcall AdvSmoothButton_ResetClick(TObject *Sender);
	void __fastcall AdvSmoothButton_ServoOffClick(TObject *Sender);
	void __fastcall AdvSmoothButton13Click(TObject *Sender);
	void __fastcall AdvSmoothButton14Click(TObject *Sender);
	void __fastcall AdvSmoothButton12Click(TObject *Sender);
	void __fastcall AdvSmoothButton11Click(TObject *Sender);
	void __fastcall AdvSmoothButton36Click(TObject *Sender);
	void __fastcall AdvSmoothButton35Click(TObject *Sender);
	void __fastcall AdvSmoothButton37Click(TObject *Sender);
	void __fastcall AdvSmoothButton38Click(TObject *Sender);
	void __fastcall speedEditKeyDown(TObject *Sender, WORD &Key, TShiftState Shift);
	void __fastcall teachingTimerTimer(TObject *Sender);
	void __fastcall AdvSmoothButton4Click(TObject *Sender);
	void __fastcall AdvSmoothButton3Click(TObject *Sender);
	void __fastcall disableChk1Click(TObject *Sender);
	void __fastcall waitBtnClick(TObject *Sender);
	void __fastcall rdo48Click(TObject *Sender);
	void __fastcall rdo96Click(TObject *Sender);
	void __fastcall openBtnClick(TObject *Sender);
	void __fastcall Button1MouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
		  int X, int Y);
	void __fastcall Button2MouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift, int X, int Y);
	void __fastcall Button1MouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
		  int X, int Y);
	void __fastcall AdvSmoothButton_ServoOnClick(TObject *Sender);
	void __fastcall applyBtnClick(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall AdvSmoothButton_ZupClick(TObject *Sender);
	void __fastcall homeBtnClick(TObject *Sender);
	void __fastcall stopBtnClick(TObject *Sender);
	void __fastcall AdvSmoothButton_CenteringDownClick(TObject *Sender);
	void __fastcall AdvSmoothButton_LoadFactorInfoClick(TObject *Sender);
	void __fastcall AdvSmoothButton1Click(TObject *Sender);
	void __fastcall AdvSmoothButton2Click(TObject *Sender);
	void __fastcall searchListClick(TObject *Sender);
	void __fastcall rdo482Click(TObject *Sender);
	void __fastcall msa482Click(TObject *Sender);
	void __fastcall msa96Click(TObject *Sender);
	void __fastcall msa48Click(TObject *Sender);
	void __fastcall Panel47Click(TObject *Sender);
	void __fastcall rbSetTeachingValueEdit(TObject *Sender);
    void __fastcall rdoChangeTrayMap(TObject *Sender);
	void __fastcall btnZAxisDownMouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall btnZAxisDownMouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall btnZAxisUpMouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall btnZAxisUpMouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall Label6Click(TObject *Sender);
	void __fastcall btnKeyLockClick(TObject *Sender);
	void __fastcall AdvSmoothButton12MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
	void __fastcall AdvSmoothButton12MouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall unchuckTimerTimer(TObject *Sender);
	void __fastcall AdvSmoothButton37MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
	void __fastcall AdvSmoothButton37MouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall unchuckAllTimerTimer(TObject *Sender);
private:	// User declarations
    TListItem	*ITEM;
	TAdvSmoothPanel *sTray[96];
	TAdvSmoothPanel *tTray[24];
	void __fastcall ChangeTrayMap(int channel);

	TEACHING teach;

	void __fastcall ApplyTeaching();
	void __fastcall LoadTeaching();

	AnsiString file;

	void __fastcall SetTrayMaxPosition();
	bool __fastcall CheckPositionDown(int gripperIndex);
	bool __fastcall CheckUnchuckPosition(int gripperIndex);
    bool __fastcall CheckChuckPosition(int gripperIndex);
    bool __fastcall CheckMoveTargetChannel(int channel);
    bool __fastcall CheckMoveSourceChannel();
//	int __fastcall FindList(UnicodeString strName);
	void __fastcall AddList(int index);
	void __fastcall SaveToFile();
	void __fastcall LoadFromFile();

    //* 마우스 버튼 3초이상 클릭시 UnCheck
    TDateTime downTime;
	bool isButtonPressed;
    int nCurrentTag;
public:		// User declarations

	TEdit *teachEdit[2][8], *teachEdit_z[2];        //  [X / Y][Source / Target]
	TEdit *teachEdit_CHUCK[2];
    TLabel *lblLoadFactor[7];
    void __fastcall zdown();
    void __fastcall zup();
	int __fastcall FindList(UnicodeString strName);
	void __fastcall LanguageChange(int index);
    void __fastcall ChangeTeaching(int index);
	TRAY_POSITION sTray_Position, tTray_Position;

	bool isGripperOpen1;
    bool isGripperOpen2;

	__fastcall TteachForm(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TteachForm *teachForm;
//---------------------------------------------------------------------------
#endif
