object AccessForm: TAccessForm
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'User access'
  ClientHeight = 452
  ClientWidth = 680
  Color = 14737632
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  Position = poScreenCenter
  Scaled = False
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 19
  object pnlTitle: TPanel
    Left = 30
    Top = 24
    Width = 194
    Height = 42
    BevelOuter = bvNone
    Caption = 'Password Input'
    Color = 4587690
    ParentBackground = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -20
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    Cursor = crHandPoint
    Hint = 'View permissions by level'
    ShowHint = True
    OnClick = pnlTitleClick
  end
  object pnlLogin: TPanel
    Left = 30
    Top = 66
    Width = 610
    Height = 154
    BevelOuter = bvNone
    Caption = ''
    Color = 14737632
    ParentBackground = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -18
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    BorderStyle = bsSingle
    TabOrder = 0
    object pnlLevel: TPanel
      Left = 12
      Top = 12
      Width = 88
      Height = 60
      BevelOuter = bvNone
      Caption = 'Level'
      Color = 10863554
      ParentBackground = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -18
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object btnOperator: TAdvSmoothButton
      Left = 104
      Top = 12
      Width = 108
      Height = 60
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clBlack
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'Operator'
      Color = 2999689
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 1
      OnClick = btnOperatorClick
    end
    object btnEngineer: TAdvSmoothButton
      Left = 216
      Top = 12
      Width = 108
      Height = 60
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clWhite
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'Engineer'
      Color = 7170148
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 2
      OnClick = btnEngineerClick
    end
    object btnAdmin: TAdvSmoothButton
      Left = 328
      Top = 12
      Width = 108
      Height = 60
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clWhite
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'Admin'
      Color = 7170148
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 3
      OnClick = btnAdminClick
    end
    object btnPasswordChange: TAdvSmoothButton
      Left = 440
      Top = 12
      Width = 154
      Height = 60
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clWhite
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'Password Change'
      Color = 7170148
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 4
      OnClick = btnPasswordChangeClick
    end
    object pnlLoginPassword: TPanel
      Left = 12
      Top = 78
      Width = 88
      Height = 60
      BevelOuter = bvNone
      Caption = 'Password'
      Color = 10863554
      ParentBackground = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -18
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object pnlPasswordEntry: TPanel
      Left = 104
      Top = 78
      Width = 332
      Height = 60
      BevelOuter = bvNone
      Caption = ''
      Color = clWhite
      ParentBackground = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -18
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      BorderStyle = bsSingle
      TabOrder = 6
      object editLoginPassword: TEdit
        Left = 6
        Top = 12
        Width = 316
        Height = 32
        Alignment = taCenter
        AutoSize = False
        BorderStyle = bsNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -22
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        MaxLength = 128
        PasswordChar = '*'
        ShowHint = True
        TabOrder = 0
        OnKeyDown = editCredentialKeyDown
      end
    end
    object btnLogout: TAdvSmoothButton
      Left = 440
      Top = 78
      Width = 154
      Height = 60
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clLime
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'LogOut'
      Color = 7170148
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 7
      OnClick = btnLogoutClick
    end
  end
  object pnlNewPasswordTitle: TPanel
    Left = 30
    Top = 276
    Width = 194
    Height = 42
    BevelOuter = bvNone
    Caption = 'New Password'
    Color = 12462096
    ParentBackground = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -20
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
  end
  object pnlNewPassword: TPanel
    Left = 30
    Top = 318
    Width = 610
    Height = 82
    BevelOuter = bvNone
    Caption = ''
    Color = 14737632
    ParentBackground = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -18
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    BorderStyle = bsSingle
    TabOrder = 1
    object pnlNewPasswordInput: TPanel
      Left = 12
      Top = 12
      Width = 88
      Height = 54
      BevelOuter = bvNone
      Caption = 'Input'
      Color = 10863554
      ParentBackground = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -18
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object pnlNewPasswordEntry: TPanel
      Left = 104
      Top = 12
      Width = 332
      Height = 54
      BevelOuter = bvNone
      Caption = ''
      Color = clWhite
      ParentBackground = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -18
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      BorderStyle = bsSingle
      TabOrder = 1
      object editNewPassword: TEdit
        Left = 6
        Top = 12
        Width = 316
        Height = 32
        Alignment = taCenter
        AutoSize = False
        BorderStyle = bsNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -22
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        MaxLength = 128
        PasswordChar = '*'
        ShowHint = True
        TabOrder = 0
        OnKeyDown = editCredentialKeyDown
        Enabled = False
      end
    end
    object btnPasswordSave: TAdvSmoothButton
      Left = 440
      Top = 12
      Width = 154
      Height = 54
      Appearance.Font.Charset = DEFAULT_CHARSET
      Appearance.Font.Color = clBlack
      Appearance.Font.Height = -18
      Appearance.Font.Name = 'Tahoma'
      Appearance.Font.Style = []
      Appearance.Rounding = 0
      Appearance.SimpleLayout = True
      Appearance.WordWrapping = True
      Caption = 'Save'
      Color = 11970637
      Enabled = False
      Bevel = False
      Shadow = False
      ParentFont = False
      TabStop = True
      TabOrder = 2
      OnClick = btnPasswordSaveClick
    end
  end
  object lblStatus: TLabel
    Left = 30
    Top = 408
    Width = 610
    Height = 36
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clMaroon
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    WordWrap = True
  end
end
